# Generated by Django 5.2 on 2025-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_comments_exchangeproposal_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
